import { getDb, upsertEvent } from "../src/lib/db";

const sampleEvents = [
  {
    id: "kabuki-2025-01-01",
    title_ja: "壽 初春大歌舞伎",
    title_en: "New Year Kabuki Performance",
    description_ja: "新年を祝う華やかな歌舞伎公演",
    description_en: "A splendid kabuki performance celebrating the New Year",
    date_start: "2025-01-02",
    date_end: "2025-01-26",
    venue_name: "歌舞伎座",
    venue_address: "東京都中央区銀座4-12-15",
    area: "Tokyo",
    category: "kabuki",
    tags: ["traditional", "theatre", "new year"],
    price_min: 4000,
    price_max: 20000,
    source_url: "https://www.kabuki-bito.jp/theaters/kabukiza/play/847",
    source_name: "Kabuki-bito",
    image_url: "https://www.kabuki-bito.jp/uploads/images/kouen/847/kabukiza_202501_poster.jpg",
  },
  {
    id: "orchestra-nhk-2025-01",
    title_ja: "NHK交響楽団 定期公演",
    title_en: "NHK Symphony Orchestra Regular Concert",
    description_ja: "ベートーヴェン交響曲第9番「合唱」",
    description_en: "Beethoven Symphony No. 9 'Choral'",
    date_start: "2025-01-15",
    date_end: "2025-01-15",
    venue_name: "NHKホール",
    venue_address: "東京都渋谷区神南2-2-1",
    area: "Tokyo",
    category: "orchestra",
    tags: ["classical", "symphony", "beethoven"],
    price_min: 5000,
    price_max: 15000,
    source_url: "https://www.nhkso.or.jp/concert/",
    source_name: "NHK Symphony",
    image_url: null,
  },
  {
    id: "anime-parco-2025-01",
    title_ja: "呪術廻戦 渋谷事変 POP UP STORE",
    title_en: "Jujutsu Kaisen Shibuya Incident POP UP STORE",
    description_ja: "人気アニメ「呪術廻戦」の期間限定ショップ",
    description_en: "Limited-time shop for the popular anime 'Jujutsu Kaisen'",
    date_start: "2025-01-10",
    date_end: "2025-01-31",
    venue_name: "渋谷PARCO",
    venue_address: "東京都渋谷区宇田川町15-1",
    area: "Tokyo",
    category: "anime",
    tags: ["anime", "jujutsu kaisen", "pop up", "shopping"],
    price_min: null,
    price_max: null,
    source_url: "https://shibuya.parco.jp/",
    source_name: "Parco",
    image_url: null,
  },
  {
    id: "rakugo-2025-01-20",
    title_ja: "新春落語会",
    title_en: "New Year Rakugo Show",
    description_ja: "人気落語家による新春特別公演",
    description_en: "Special New Year performance by popular rakugo storytellers",
    date_start: "2025-01-20",
    date_end: "2025-01-20",
    venue_name: "国立演芸場",
    venue_address: "東京都千代田区隼町4-1",
    area: "Tokyo",
    category: "rakugo",
    tags: ["traditional", "comedy", "storytelling"],
    price_min: 2500,
    price_max: 4500,
    source_url: "http://rakugo-kyokai.jp/",
    source_name: "Rakugo Kyokai",
    image_url: null,
  },
  {
    id: "musical-2025-01",
    title_ja: "レ・ミゼラブル",
    title_en: "Les Misérables",
    description_ja: "世界的に有名なミュージカルの日本公演",
    description_en: "The world-famous musical's Japan production",
    date_start: "2025-01-05",
    date_end: "2025-03-30",
    venue_name: "帝国劇場",
    venue_address: "東京都千代田区丸の内3-1-1",
    area: "Tokyo",
    category: "musical",
    tags: ["musical", "broadway", "theatre"],
    price_min: 8000,
    price_max: 16000,
    source_url: "https://t.pia.jp/",
    source_name: "Ticket Pia",
    image_url: null,
  },
  {
    id: "concert-osaka-2025-02",
    title_ja: "大阪フィルハーモニー交響楽団 定期演奏会",
    title_en: "Osaka Philharmonic Orchestra Regular Concert",
    description_ja: "マーラー交響曲第5番",
    description_en: "Mahler Symphony No. 5",
    date_start: "2025-02-10",
    date_end: "2025-02-10",
    venue_name: "フェスティバルホール",
    venue_address: "大阪市北区中之島2-3-18",
    area: "Osaka",
    category: "orchestra",
    tags: ["classical", "symphony", "mahler"],
    price_min: 4000,
    price_max: 12000,
    source_url: "https://www.osaka-phil.com/",
    source_name: "Osaka Phil",
    image_url: null,
  },
  {
    id: "event-kyoto-2025-02",
    title_ja: "京都 節分祭",
    title_en: "Kyoto Setsubun Festival",
    description_ja: "八坂神社での豆まき行事",
    description_en: "Bean-throwing ceremony at Yasaka Shrine",
    date_start: "2025-02-03",
    date_end: "2025-02-03",
    venue_name: "八坂神社",
    venue_address: "京都市東山区祇園町北側625",
    area: "Kyoto",
    category: "festival",
    tags: ["festival", "traditional", "shrine", "free"],
    price_min: null,
    price_max: null,
    source_url: "https://en.japantravel.com/kyoto/yasaka-shrine-setsubun/12345",
    source_name: "Japan Travel",
    image_url: null,
  },
  {
    id: "art-tokyo-2025-01",
    title_ja: "チームラボ ボーダレス",
    title_en: "teamLab Borderless",
    description_ja: "デジタルアートミュージアム",
    description_en: "Digital Art Museum",
    date_start: "2025-01-01",
    date_end: "2025-12-31",
    venue_name: "麻布台ヒルズ",
    venue_address: "東京都港区麻布台1-2-4",
    area: "Tokyo",
    category: "art",
    tags: ["art", "digital", "museum", "interactive"],
    price_min: 3800,
    price_max: 3800,
    source_url: "https://www.teamlab.art/e/borderless-azabudai/",
    source_name: "teamLab",
    image_url: null,
  },
];

async function seed() {
  console.log("Initializing database...");
  getDb(); // Initialize DB and create tables

  console.log("Seeding sample events...");
  for (const event of sampleEvents) {
    upsertEvent(event);
    console.log(`  Added: ${event.title_en}`);
  }

  console.log(`\nSeeded ${sampleEvents.length} events successfully!`);
}

seed().catch(console.error);
